name: Ruff
on:
  pull_request:
    branches:
      - master
      - main
      - dev
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check . --exclude yfinance/pricing_pb2.py
